// Code generated by MockGen. DO NOT EDIT.
// Source: cache_serializer_creator.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	flam "github.com/cjdias/flam-in-go"
	gomock "github.com/golang/mock/gomock"
)

// MockCacheSerializerCreator is a mock of CacheSerializerCreator interface.
type MockCacheSerializerCreator struct {
	ctrl     *gomock.Controller
	recorder *MockCacheSerializerCreatorMockRecorder
}

// MockCacheSerializerCreatorMockRecorder is the mock recorder for MockCacheSerializerCreator.
type MockCacheSerializerCreatorMockRecorder struct {
	mock *MockCacheSerializerCreator
}

// NewMockCacheSerializerCreator creates a new mock instance.
func NewMockCacheSerializerCreator(ctrl *gomock.Controller) *MockCacheSerializerCreator {
	mock := &MockCacheSerializerCreator{ctrl: ctrl}
	mock.recorder = &MockCacheSerializerCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheSerializerCreator) EXPECT() *MockCacheSerializerCreatorMockRecorder {
	return m.recorder
}

// Accept mocks base method.
func (m *MockCacheSerializerCreator) Accept(config flam.Bag) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Accept", config)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Accept indicates an expected call of Accept.
func (mr *MockCacheSerializerCreatorMockRecorder) Accept(config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Accept", reflect.TypeOf((*MockCacheSerializerCreator)(nil).Accept), config)
}

// Create mocks base method.
func (m *MockCacheSerializerCreator) Create(config flam.Bag) (flam.CacheSerializer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", config)
	ret0, _ := ret[0].(flam.CacheSerializer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCacheSerializerCreatorMockRecorder) Create(config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCacheSerializerCreator)(nil).Create), config)
}
