// Code generated by MockGen. DO NOT EDIT.
// Source: cache_serializer.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCacheSerializer is a mock of CacheSerializer interface.
type MockCacheSerializer struct {
	ctrl     *gomock.Controller
	recorder *MockCacheSerializerMockRecorder
}

// MockCacheSerializerMockRecorder is the mock recorder for MockCacheSerializer.
type MockCacheSerializerMockRecorder struct {
	mock *MockCacheSerializer
}

// NewMockCacheSerializer creates a new mock instance.
func NewMockCacheSerializer(ctrl *gomock.Controller) *MockCacheSerializer {
	mock := &MockCacheSerializer{ctrl: ctrl}
	mock.recorder = &MockCacheSerializerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheSerializer) EXPECT() *MockCacheSerializerMockRecorder {
	return m.recorder
}

// Deserialize mocks base method.
func (m *MockCacheSerializer) Deserialize(data string, obj any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deserialize", data, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deserialize indicates an expected call of Deserialize.
func (mr *MockCacheSerializerMockRecorder) Deserialize(data, obj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deserialize", reflect.TypeOf((*MockCacheSerializer)(nil).Deserialize), data, obj)
}

// Serialize mocks base method.
func (m *MockCacheSerializer) Serialize(obj any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Serialize", obj)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Serialize indicates an expected call of Serialize.
func (mr *MockCacheSerializerMockRecorder) Serialize(obj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Serialize", reflect.TypeOf((*MockCacheSerializer)(nil).Serialize), obj)
}
