// Code generated by MockGen. DO NOT EDIT.
// Source: cache_adaptor.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockCacheAdaptor is a mock of CacheAdaptor interface.
type MockCacheAdaptor struct {
	ctrl     *gomock.Controller
	recorder *MockCacheAdaptorMockRecorder
}

// MockCacheAdaptorMockRecorder is the mock recorder for MockCacheAdaptor.
type MockCacheAdaptorMockRecorder struct {
	mock *MockCacheAdaptor
}

// NewMockCacheAdaptor creates a new mock instance.
func NewMockCacheAdaptor(ctrl *gomock.Controller) *MockCacheAdaptor {
	mock := &MockCacheAdaptor{ctrl: ctrl}
	mock.recorder = &MockCacheAdaptorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheAdaptor) EXPECT() *MockCacheAdaptorMockRecorder {
	return m.recorder
}

// Del mocks base method.
func (m *MockCacheAdaptor) Del(obj ...any) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range obj {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Del", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Del indicates an expected call of Del.
func (mr *MockCacheAdaptorMockRecorder) Del(obj ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockCacheAdaptor)(nil).Del), obj...)
}

// Get mocks base method.
func (m *MockCacheAdaptor) Get(obj ...any) ([]any, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range obj {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].([]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCacheAdaptorMockRecorder) Get(obj ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCacheAdaptor)(nil).Get), obj...)
}

// Has mocks base method.
func (m *MockCacheAdaptor) Has(obj ...any) ([]bool, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range obj {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Has", varargs...)
	ret0, _ := ret[0].([]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Has indicates an expected call of Has.
func (mr *MockCacheAdaptorMockRecorder) Has(obj ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Has", reflect.TypeOf((*MockCacheAdaptor)(nil).Has), obj...)
}

// Set mocks base method.
func (m *MockCacheAdaptor) Set(obj ...any) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range obj {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Set", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockCacheAdaptorMockRecorder) Set(obj ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCacheAdaptor)(nil).Set), obj...)
}

// SetEphemeral mocks base method.
func (m *MockCacheAdaptor) SetEphemeral(ttl time.Duration, obj ...any) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ttl}
	for _, a := range obj {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetEphemeral", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetEphemeral indicates an expected call of SetEphemeral.
func (mr *MockCacheAdaptorMockRecorder) SetEphemeral(ttl interface{}, obj ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ttl}, obj...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEphemeral", reflect.TypeOf((*MockCacheAdaptor)(nil).SetEphemeral), varargs...)
}
