// Code generated by MockGen. DO NOT EDIT.
// Source: cache_key_generator_creator.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	flam "github.com/cjdias/flam-in-go"
	gomock "github.com/golang/mock/gomock"
)

// MockCacheKeyGeneratorCreator is a mock of CacheKeyGeneratorCreator interface.
type MockCacheKeyGeneratorCreator struct {
	ctrl     *gomock.Controller
	recorder *MockCacheKeyGeneratorCreatorMockRecorder
}

// MockCacheKeyGeneratorCreatorMockRecorder is the mock recorder for MockCacheKeyGeneratorCreator.
type MockCacheKeyGeneratorCreatorMockRecorder struct {
	mock *MockCacheKeyGeneratorCreator
}

// NewMockCacheKeyGeneratorCreator creates a new mock instance.
func NewMockCacheKeyGeneratorCreator(ctrl *gomock.Controller) *MockCacheKeyGeneratorCreator {
	mock := &MockCacheKeyGeneratorCreator{ctrl: ctrl}
	mock.recorder = &MockCacheKeyGeneratorCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheKeyGeneratorCreator) EXPECT() *MockCacheKeyGeneratorCreatorMockRecorder {
	return m.recorder
}

// Accept mocks base method.
func (m *MockCacheKeyGeneratorCreator) Accept(config flam.Bag) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Accept", config)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Accept indicates an expected call of Accept.
func (mr *MockCacheKeyGeneratorCreatorMockRecorder) Accept(config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Accept", reflect.TypeOf((*MockCacheKeyGeneratorCreator)(nil).Accept), config)
}

// Create mocks base method.
func (m *MockCacheKeyGeneratorCreator) Create(config flam.Bag) (flam.CacheKeyGenerator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", config)
	ret0, _ := ret[0].(flam.CacheKeyGenerator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCacheKeyGeneratorCreatorMockRecorder) Create(config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCacheKeyGeneratorCreator)(nil).Create), config)
}
