// Code generated by MockGen. DO NOT EDIT.
// Source: cache_adaptor_creator.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	flam "github.com/cjdias/flam-in-go"
	gomock "github.com/golang/mock/gomock"
)

// MockCacheAdaptorCreator is a mock of CacheAdaptorCreator interface.
type MockCacheAdaptorCreator struct {
	ctrl     *gomock.Controller
	recorder *MockCacheAdaptorCreatorMockRecorder
}

// MockCacheAdaptorCreatorMockRecorder is the mock recorder for MockCacheAdaptorCreator.
type MockCacheAdaptorCreatorMockRecorder struct {
	mock *MockCacheAdaptorCreator
}

// NewMockCacheAdaptorCreator creates a new mock instance.
func NewMockCacheAdaptorCreator(ctrl *gomock.Controller) *MockCacheAdaptorCreator {
	mock := &MockCacheAdaptorCreator{ctrl: ctrl}
	mock.recorder = &MockCacheAdaptorCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheAdaptorCreator) EXPECT() *MockCacheAdaptorCreatorMockRecorder {
	return m.recorder
}

// Accept mocks base method.
func (m *MockCacheAdaptorCreator) Accept(config flam.Bag) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Accept", config)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Accept indicates an expected call of Accept.
func (mr *MockCacheAdaptorCreatorMockRecorder) Accept(config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Accept", reflect.TypeOf((*MockCacheAdaptorCreator)(nil).Accept), config)
}

// Create mocks base method.
func (m *MockCacheAdaptorCreator) Create(config flam.Bag) (flam.CacheAdaptor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", config)
	ret0, _ := ret[0].(flam.CacheAdaptor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCacheAdaptorCreatorMockRecorder) Create(config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCacheAdaptorCreator)(nil).Create), config)
}
