// Code generated by MockGen. DO NOT EDIT.
// Source: config_source_creator.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	flam "github.com/cjdias/flam-in-go"
	gomock "github.com/golang/mock/gomock"
)

// MockConfigSourceCreator is a mock of ConfigSourceCreator interface.
type MockConfigSourceCreator struct {
	ctrl     *gomock.Controller
	recorder *MockConfigSourceCreatorMockRecorder
}

// MockConfigSourceCreatorMockRecorder is the mock recorder for MockConfigSourceCreator.
type MockConfigSourceCreatorMockRecorder struct {
	mock *MockConfigSourceCreator
}

// NewMockConfigSourceCreator creates a new mock instance.
func NewMockConfigSourceCreator(ctrl *gomock.Controller) *MockConfigSourceCreator {
	mock := &MockConfigSourceCreator{ctrl: ctrl}
	mock.recorder = &MockConfigSourceCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigSourceCreator) EXPECT() *MockConfigSourceCreatorMockRecorder {
	return m.recorder
}

// Accept mocks base method.
func (m *MockConfigSourceCreator) Accept(config flam.Bag) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Accept", config)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Accept indicates an expected call of Accept.
func (mr *MockConfigSourceCreatorMockRecorder) Accept(config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Accept", reflect.TypeOf((*MockConfigSourceCreator)(nil).Accept), config)
}

// Create mocks base method.
func (m *MockConfigSourceCreator) Create(config flam.Bag) (flam.ConfigSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", config)
	ret0, _ := ret[0].(flam.ConfigSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockConfigSourceCreatorMockRecorder) Create(config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockConfigSourceCreator)(nil).Create), config)
}
