// Code generated by MockGen. DO NOT EDIT.
// Source: config_source.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockConfigSource is a mock of ConfigSource interface.
type MockConfigSource struct {
	ctrl     *gomock.Controller
	recorder *MockConfigSourceMockRecorder
}

// MockConfigSourceMockRecorder is the mock recorder for MockConfigSource.
type MockConfigSourceMockRecorder struct {
	mock *MockConfigSource
}

// NewMockConfigSource creates a new mock instance.
func NewMockConfigSource(ctrl *gomock.Controller) *MockConfigSource {
	mock := &MockConfigSource{ctrl: ctrl}
	mock.recorder = &MockConfigSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigSource) EXPECT() *MockConfigSourceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockConfigSource) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockConfigSourceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockConfigSource)(nil).Close))
}

// Get mocks base method.
func (m *MockConfigSource) Get(path string, def ...any) any {
	m.ctrl.T.Helper()
	varargs := []interface{}{path}
	for _, a := range def {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(any)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockConfigSourceMockRecorder) Get(path interface{}, def ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{path}, def...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockConfigSource)(nil).Get), varargs...)
}

// GetPriority mocks base method.
func (m *MockConfigSource) GetPriority() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPriority")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetPriority indicates an expected call of GetPriority.
func (mr *MockConfigSourceMockRecorder) GetPriority() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPriority", reflect.TypeOf((*MockConfigSource)(nil).GetPriority))
}

// SetPriority mocks base method.
func (m *MockConfigSource) SetPriority(priority int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetPriority", priority)
}

// SetPriority indicates an expected call of SetPriority.
func (mr *MockConfigSourceMockRecorder) SetPriority(priority interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPriority", reflect.TypeOf((*MockConfigSource)(nil).SetPriority), priority)
}

// MockObservableConfigSource is a mock of ObservableConfigSource interface.
type MockObservableConfigSource struct {
	ctrl     *gomock.Controller
	recorder *MockObservableConfigSourceMockRecorder
}

// MockObservableConfigSourceMockRecorder is the mock recorder for MockObservableConfigSource.
type MockObservableConfigSourceMockRecorder struct {
	mock *MockObservableConfigSource
}

// NewMockObservableConfigSource creates a new mock instance.
func NewMockObservableConfigSource(ctrl *gomock.Controller) *MockObservableConfigSource {
	mock := &MockObservableConfigSource{ctrl: ctrl}
	mock.recorder = &MockObservableConfigSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObservableConfigSource) EXPECT() *MockObservableConfigSourceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockObservableConfigSource) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockObservableConfigSourceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockObservableConfigSource)(nil).Close))
}

// Get mocks base method.
func (m *MockObservableConfigSource) Get(path string, def ...any) any {
	m.ctrl.T.Helper()
	varargs := []interface{}{path}
	for _, a := range def {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(any)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockObservableConfigSourceMockRecorder) Get(path interface{}, def ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{path}, def...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockObservableConfigSource)(nil).Get), varargs...)
}

// GetPriority mocks base method.
func (m *MockObservableConfigSource) GetPriority() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPriority")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetPriority indicates an expected call of GetPriority.
func (mr *MockObservableConfigSourceMockRecorder) GetPriority() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPriority", reflect.TypeOf((*MockObservableConfigSource)(nil).GetPriority))
}

// Reload mocks base method.
func (m *MockObservableConfigSource) Reload() (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reload")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reload indicates an expected call of Reload.
func (mr *MockObservableConfigSourceMockRecorder) Reload() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reload", reflect.TypeOf((*MockObservableConfigSource)(nil).Reload))
}

// SetPriority mocks base method.
func (m *MockObservableConfigSource) SetPriority(priority int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetPriority", priority)
}

// SetPriority indicates an expected call of SetPriority.
func (mr *MockObservableConfigSourceMockRecorder) SetPriority(priority interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPriority", reflect.TypeOf((*MockObservableConfigSource)(nil).SetPriority), priority)
}
