// Code generated by MockGen. DO NOT EDIT.
// Source: config_rest_client_generator.go

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	flam "github.com/cjdias/flam-in-go"
	gomock "github.com/golang/mock/gomock"
)

// MockConfigRestClientGenerator is a mock of ConfigRestClientGenerator interface.
type MockConfigRestClientGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockConfigRestClientGeneratorMockRecorder
}

// MockConfigRestClientGeneratorMockRecorder is the mock recorder for MockConfigRestClientGenerator.
type MockConfigRestClientGeneratorMockRecorder struct {
	mock *MockConfigRestClientGenerator
}

// NewMockConfigRestClientGenerator creates a new mock instance.
func NewMockConfigRestClientGenerator(ctrl *gomock.Controller) *MockConfigRestClientGenerator {
	mock := &MockConfigRestClientGenerator{ctrl: ctrl}
	mock.recorder = &MockConfigRestClientGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigRestClientGenerator) EXPECT() *MockConfigRestClientGeneratorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockConfigRestClientGenerator) Create() (flam.ConfigRestClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create")
	ret0, _ := ret[0].(flam.ConfigRestClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockConfigRestClientGeneratorMockRecorder) Create() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockConfigRestClientGenerator)(nil).Create))
}

// MockConfigRestClient is a mock of ConfigRestClient interface.
type MockConfigRestClient struct {
	ctrl     *gomock.Controller
	recorder *MockConfigRestClientMockRecorder
}

// MockConfigRestClientMockRecorder is the mock recorder for MockConfigRestClient.
type MockConfigRestClientMockRecorder struct {
	mock *MockConfigRestClient
}

// NewMockConfigRestClient creates a new mock instance.
func NewMockConfigRestClient(ctrl *gomock.Controller) *MockConfigRestClient {
	mock := &MockConfigRestClient{ctrl: ctrl}
	mock.recorder = &MockConfigRestClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigRestClient) EXPECT() *MockConfigRestClientMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockConfigRestClient) Do(req *http.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", req)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockConfigRestClientMockRecorder) Do(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockConfigRestClient)(nil).Do), req)
}
