// Code generated by MockGen. DO NOT EDIT.
// Source: database_dialect.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gorm "gorm.io/gorm"
	clause "gorm.io/gorm/clause"
	schema "gorm.io/gorm/schema"
)

// MockDatabaseDialect is a mock of DatabaseDialect interface.
type MockDatabaseDialect struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseDialectMockRecorder
}

// MockDatabaseDialectMockRecorder is the mock recorder for MockDatabaseDialect.
type MockDatabaseDialectMockRecorder struct {
	mock *MockDatabaseDialect
}

// NewMockDatabaseDialect creates a new mock instance.
func NewMockDatabaseDialect(ctrl *gomock.Controller) *MockDatabaseDialect {
	mock := &MockDatabaseDialect{ctrl: ctrl}
	mock.recorder = &MockDatabaseDialectMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabaseDialect) EXPECT() *MockDatabaseDialectMockRecorder {
	return m.recorder
}

// BindVarTo mocks base method.
func (m *MockDatabaseDialect) BindVarTo(writer clause.Writer, stmt *gorm.Statement, v interface{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BindVarTo", writer, stmt, v)
}

// BindVarTo indicates an expected call of BindVarTo.
func (mr *MockDatabaseDialectMockRecorder) BindVarTo(writer, stmt, v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BindVarTo", reflect.TypeOf((*MockDatabaseDialect)(nil).BindVarTo), writer, stmt, v)
}

// DataTypeOf mocks base method.
func (m *MockDatabaseDialect) DataTypeOf(arg0 *schema.Field) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DataTypeOf", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// DataTypeOf indicates an expected call of DataTypeOf.
func (mr *MockDatabaseDialectMockRecorder) DataTypeOf(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataTypeOf", reflect.TypeOf((*MockDatabaseDialect)(nil).DataTypeOf), arg0)
}

// DefaultValueOf mocks base method.
func (m *MockDatabaseDialect) DefaultValueOf(arg0 *schema.Field) clause.Expression {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefaultValueOf", arg0)
	ret0, _ := ret[0].(clause.Expression)
	return ret0
}

// DefaultValueOf indicates an expected call of DefaultValueOf.
func (mr *MockDatabaseDialectMockRecorder) DefaultValueOf(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefaultValueOf", reflect.TypeOf((*MockDatabaseDialect)(nil).DefaultValueOf), arg0)
}

// Explain mocks base method.
func (m *MockDatabaseDialect) Explain(sql string, vars ...interface{}) string {
	m.ctrl.T.Helper()
	varargs := []interface{}{sql}
	for _, a := range vars {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Explain", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// Explain indicates an expected call of Explain.
func (mr *MockDatabaseDialectMockRecorder) Explain(sql interface{}, vars ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{sql}, vars...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Explain", reflect.TypeOf((*MockDatabaseDialect)(nil).Explain), varargs...)
}

// Initialize mocks base method.
func (m *MockDatabaseDialect) Initialize(arg0 *gorm.DB) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initialize", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Initialize indicates an expected call of Initialize.
func (mr *MockDatabaseDialectMockRecorder) Initialize(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initialize", reflect.TypeOf((*MockDatabaseDialect)(nil).Initialize), arg0)
}

// Migrator mocks base method.
func (m *MockDatabaseDialect) Migrator(db *gorm.DB) gorm.Migrator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Migrator", db)
	ret0, _ := ret[0].(gorm.Migrator)
	return ret0
}

// Migrator indicates an expected call of Migrator.
func (mr *MockDatabaseDialectMockRecorder) Migrator(db interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Migrator", reflect.TypeOf((*MockDatabaseDialect)(nil).Migrator), db)
}

// Name mocks base method.
func (m *MockDatabaseDialect) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockDatabaseDialectMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockDatabaseDialect)(nil).Name))
}

// QuoteTo mocks base method.
func (m *MockDatabaseDialect) QuoteTo(arg0 clause.Writer, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "QuoteTo", arg0, arg1)
}

// QuoteTo indicates an expected call of QuoteTo.
func (mr *MockDatabaseDialectMockRecorder) QuoteTo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuoteTo", reflect.TypeOf((*MockDatabaseDialect)(nil).QuoteTo), arg0, arg1)
}
