// Code generated by MockGen. DO NOT EDIT.
// Source: disk_factory.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	flam "github.com/cjdias/flam-in-go"
	gomock "github.com/golang/mock/gomock"
)

// MockDiskFactory is a mock of DiskFactory interface.
type MockDiskFactory struct {
	ctrl     *gomock.Controller
	recorder *MockDiskFactoryMockRecorder
}

// MockDiskFactoryMockRecorder is the mock recorder for MockDiskFactory.
type MockDiskFactoryMockRecorder struct {
	mock *MockDiskFactory
}

// NewMockDiskFactory creates a new mock instance.
func NewMockDiskFactory(ctrl *gomock.Controller) *MockDiskFactory {
	mock := &MockDiskFactory{ctrl: ctrl}
	mock.recorder = &MockDiskFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiskFactory) EXPECT() *MockDiskFactoryMockRecorder {
	return m.recorder
}

// Available mocks base method.
func (m *MockDiskFactory) Available() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Available")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Available indicates an expected call of Available.
func (mr *MockDiskFactoryMockRecorder) Available() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Available", reflect.TypeOf((*MockDiskFactory)(nil).Available))
}

// Close mocks base method.
func (m *MockDiskFactory) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDiskFactoryMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDiskFactory)(nil).Close))
}

// Get mocks base method.
func (m *MockDiskFactory) Get(id string) (flam.Disk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(flam.Disk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDiskFactoryMockRecorder) Get(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDiskFactory)(nil).Get), id)
}

// Has mocks base method.
func (m *MockDiskFactory) Has(id string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Has", id)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Has indicates an expected call of Has.
func (mr *MockDiskFactoryMockRecorder) Has(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Has", reflect.TypeOf((*MockDiskFactory)(nil).Has), id)
}

// Remove mocks base method.
func (m *MockDiskFactory) Remove(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockDiskFactoryMockRecorder) Remove(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockDiskFactory)(nil).Remove), id)
}

// RemoveAll mocks base method.
func (m *MockDiskFactory) RemoveAll() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAll")
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAll indicates an expected call of RemoveAll.
func (mr *MockDiskFactoryMockRecorder) RemoveAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAll", reflect.TypeOf((*MockDiskFactory)(nil).RemoveAll))
}

// Store mocks base method.
func (m *MockDiskFactory) Store(id string, disk flam.Disk) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", id, disk)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockDiskFactoryMockRecorder) Store(id, disk interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockDiskFactory)(nil).Store), id, disk)
}

// Stored mocks base method.
func (m *MockDiskFactory) Stored() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stored")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Stored indicates an expected call of Stored.
func (mr *MockDiskFactoryMockRecorder) Stored() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stored", reflect.TypeOf((*MockDiskFactory)(nil).Stored))
}
