// Code generated by MockGen. DO NOT EDIT.
// Source: factory.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	flam "github.com/cjdias/flam-in-go"
)

// MockFactoryResourceCreator is a mock of FactoryResourceCreator interface.
type MockFactoryResourceCreator[R flam.FactoryResource] struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryResourceCreatorMockRecorder[R]
}

// MockFactoryResourceCreatorMockRecorder is the mock recorder for MockFactoryResourceCreator.
type MockFactoryResourceCreatorMockRecorder[R flam.FactoryResource] struct {
	mock *MockFactoryResourceCreator[R]
}

// NewMockFactoryResourceCreator creates a new mock instance.
func NewMockFactoryResourceCreator[R flam.FactoryResource](ctrl *gomock.Controller) *MockFactoryResourceCreator[R] {
	mock := &MockFactoryResourceCreator[R]{ctrl: ctrl}
	mock.recorder = &MockFactoryResourceCreatorMockRecorder[R]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactoryResourceCreator[R]) EXPECT() *MockFactoryResourceCreatorMockRecorder[R] {
	return m.recorder
}

// Accept mocks base method.
func (m *MockFactoryResourceCreator[R]) Accept(config flam.Bag) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Accept", config)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Accept indicates an expected call of Accept.
func (mr *MockFactoryResourceCreatorMockRecorder[R]) Accept(config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Accept", reflect.TypeOf((*MockFactoryResourceCreator[R])(nil).Accept), config)
}

// Create mocks base method.
func (m *MockFactoryResourceCreator[R]) Create(config flam.Bag) (R, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", config)
	ret0, _ := ret[0].(R)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockFactoryResourceCreatorMockRecorder[R]) Create(config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFactoryResourceCreator[R])(nil).Create), config)
}

// MockFactory is a mock of Factory interface.
type MockFactory[R flam.FactoryResource] struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder[R]
}

// MockFactoryMockRecorder is the mock recorder for MockFactory.
type MockFactoryMockRecorder[R flam.FactoryResource] struct {
	mock *MockFactory[R]
}

// NewMockFactory creates a new mock instance.
func NewMockFactory[R flam.FactoryResource](ctrl *gomock.Controller) *MockFactory[R] {
	mock := &MockFactory[R]{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder[R]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactory[R]) EXPECT() *MockFactoryMockRecorder[R] {
	return m.recorder
}

// Available mocks base method.
func (m *MockFactory[R]) Available() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Available")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Available indicates an expected call of Available.
func (mr *MockFactoryMockRecorder[R]) Available() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Available", reflect.TypeOf((*MockFactory[R])(nil).Available))
}

// Close mocks base method.
func (m *MockFactory[R]) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockFactoryMockRecorder[R]) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockFactory[R])(nil).Close))
}

// Generate mocks base method.
func (m *MockFactory[R]) Generate(id string) (R, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", id)
	ret0, _ := ret[0].(R)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockFactoryMockRecorder[R]) Generate(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockFactory[R])(nil).Generate), id)
}

// GenerateAll mocks base method.
func (m *MockFactory[R]) GenerateAll() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAll")
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateAll indicates an expected call of GenerateAll.
func (mr *MockFactoryMockRecorder[R]) GenerateAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAll", reflect.TypeOf((*MockFactory[R])(nil).GenerateAll))
}

// Get mocks base method.
func (m *MockFactory[R]) Get(id string) (R, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(R)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockFactoryMockRecorder[R]) Get(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockFactory[R])(nil).Get), id)
}

// Has mocks base method.
func (m *MockFactory[R]) Has(id string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Has", id)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Has indicates an expected call of Has.
func (mr *MockFactoryMockRecorder[R]) Has(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Has", reflect.TypeOf((*MockFactory[R])(nil).Has), id)
}

// Remove mocks base method.
func (m *MockFactory[R]) Remove(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockFactoryMockRecorder[R]) Remove(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockFactory[R])(nil).Remove), id)
}

// RemoveAll mocks base method.
func (m *MockFactory[R]) RemoveAll() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAll")
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAll indicates an expected call of RemoveAll.
func (mr *MockFactoryMockRecorder[R]) RemoveAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAll", reflect.TypeOf((*MockFactory[R])(nil).RemoveAll))
}

// Store mocks base method.
func (m *MockFactory[R]) Store(id string, value R) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", id, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockFactoryMockRecorder[R]) Store(id, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockFactory[R])(nil).Store), id, value)
}

// Stored mocks base method.
func (m *MockFactory[R]) Stored() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stored")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Stored indicates an expected call of Stored.
func (mr *MockFactoryMockRecorder[R]) Stored() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stored", reflect.TypeOf((*MockFactory[R])(nil).Stored))
}
