// Code generated by MockGen. DO NOT EDIT.
// Source: factory_config.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	flam "github.com/cjdias/flam-in-go"
)

// MockFactoryConfig is a mock of FactoryConfig interface.
type MockFactoryConfig struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryConfigMockRecorder
}

// MockFactoryConfigMockRecorder is the mock recorder for MockFactoryConfig.
type MockFactoryConfigMockRecorder struct {
	mock *MockFactoryConfig
}

// NewMockFactoryConfig creates a new mock instance.
func NewMockFactoryConfig(ctrl *gomock.Controller) *MockFactoryConfig {
	mock := &MockFactoryConfig{ctrl: ctrl}
	mock.recorder = &MockFactoryConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactoryConfig) EXPECT() *MockFactoryConfigMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockFactoryConfig) Get(path string, def ...any) flam.Bag {
	m.ctrl.T.Helper()
	varargs := []interface{}{path}
	for _, a := range def {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(flam.Bag)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockFactoryConfigMockRecorder) Get(path interface{}, def ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{path}, def...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockFactoryConfig)(nil).Get), varargs...)
}
