// Code generated by MockGen. DO NOT EDIT.
// Source: log.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	flam "github.com/cjdias/flam-in-go"
	gomock "github.com/golang/mock/gomock"
)

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Broadcast mocks base method.
func (m *MockLogger) Broadcast(level flam.LogLevel, message string, ctx ...flam.Bag) {
	m.ctrl.T.Helper()
	varargs := []interface{}{level, message}
	for _, a := range ctx {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Broadcast", varargs...)
}

// Broadcast indicates an expected call of Broadcast.
func (mr *MockLoggerMockRecorder) Broadcast(level, message interface{}, ctx ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{level, message}, ctx...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Broadcast", reflect.TypeOf((*MockLogger)(nil).Broadcast), varargs...)
}

// BroadcastDebug mocks base method.
func (m *MockLogger) BroadcastDebug(message string, ctx ...flam.Bag) {
	m.ctrl.T.Helper()
	varargs := []interface{}{message}
	for _, a := range ctx {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "BroadcastDebug", varargs...)
}

// BroadcastDebug indicates an expected call of BroadcastDebug.
func (mr *MockLoggerMockRecorder) BroadcastDebug(message interface{}, ctx ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{message}, ctx...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastDebug", reflect.TypeOf((*MockLogger)(nil).BroadcastDebug), varargs...)
}

// BroadcastError mocks base method.
func (m *MockLogger) BroadcastError(message string, ctx ...flam.Bag) {
	m.ctrl.T.Helper()
	varargs := []interface{}{message}
	for _, a := range ctx {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "BroadcastError", varargs...)
}

// BroadcastError indicates an expected call of BroadcastError.
func (mr *MockLoggerMockRecorder) BroadcastError(message interface{}, ctx ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{message}, ctx...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastError", reflect.TypeOf((*MockLogger)(nil).BroadcastError), varargs...)
}

// BroadcastFatal mocks base method.
func (m *MockLogger) BroadcastFatal(message string, ctx ...flam.Bag) {
	m.ctrl.T.Helper()
	varargs := []interface{}{message}
	for _, a := range ctx {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "BroadcastFatal", varargs...)
}

// BroadcastFatal indicates an expected call of BroadcastFatal.
func (mr *MockLoggerMockRecorder) BroadcastFatal(message interface{}, ctx ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{message}, ctx...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastFatal", reflect.TypeOf((*MockLogger)(nil).BroadcastFatal), varargs...)
}

// BroadcastInfo mocks base method.
func (m *MockLogger) BroadcastInfo(message string, ctx ...flam.Bag) {
	m.ctrl.T.Helper()
	varargs := []interface{}{message}
	for _, a := range ctx {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "BroadcastInfo", varargs...)
}

// BroadcastInfo indicates an expected call of BroadcastInfo.
func (mr *MockLoggerMockRecorder) BroadcastInfo(message interface{}, ctx ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{message}, ctx...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastInfo", reflect.TypeOf((*MockLogger)(nil).BroadcastInfo), varargs...)
}

// BroadcastNotice mocks base method.
func (m *MockLogger) BroadcastNotice(message string, ctx ...flam.Bag) {
	m.ctrl.T.Helper()
	varargs := []interface{}{message}
	for _, a := range ctx {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "BroadcastNotice", varargs...)
}

// BroadcastNotice indicates an expected call of BroadcastNotice.
func (mr *MockLoggerMockRecorder) BroadcastNotice(message interface{}, ctx ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{message}, ctx...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastNotice", reflect.TypeOf((*MockLogger)(nil).BroadcastNotice), varargs...)
}

// BroadcastWarning mocks base method.
func (m *MockLogger) BroadcastWarning(message string, ctx ...flam.Bag) {
	m.ctrl.T.Helper()
	varargs := []interface{}{message}
	for _, a := range ctx {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "BroadcastWarning", varargs...)
}

// BroadcastWarning indicates an expected call of BroadcastWarning.
func (mr *MockLoggerMockRecorder) BroadcastWarning(message interface{}, ctx ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{message}, ctx...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastWarning", reflect.TypeOf((*MockLogger)(nil).BroadcastWarning), varargs...)
}

// Flush mocks base method.
func (m *MockLogger) Flush() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush")
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockLoggerMockRecorder) Flush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockLogger)(nil).Flush))
}

// Signal mocks base method.
func (m *MockLogger) Signal(level flam.LogLevel, channel, message string, ctx ...flam.Bag) {
	m.ctrl.T.Helper()
	varargs := []interface{}{level, channel, message}
	for _, a := range ctx {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Signal", varargs...)
}

// Signal indicates an expected call of Signal.
func (mr *MockLoggerMockRecorder) Signal(level, channel, message interface{}, ctx ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{level, channel, message}, ctx...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockLogger)(nil).Signal), varargs...)
}

// SignalDebug mocks base method.
func (m *MockLogger) SignalDebug(channel, message string, ctx ...flam.Bag) {
	m.ctrl.T.Helper()
	varargs := []interface{}{channel, message}
	for _, a := range ctx {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "SignalDebug", varargs...)
}

// SignalDebug indicates an expected call of SignalDebug.
func (mr *MockLoggerMockRecorder) SignalDebug(channel, message interface{}, ctx ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{channel, message}, ctx...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignalDebug", reflect.TypeOf((*MockLogger)(nil).SignalDebug), varargs...)
}

// SignalError mocks base method.
func (m *MockLogger) SignalError(channel, message string, ctx ...flam.Bag) {
	m.ctrl.T.Helper()
	varargs := []interface{}{channel, message}
	for _, a := range ctx {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "SignalError", varargs...)
}

// SignalError indicates an expected call of SignalError.
func (mr *MockLoggerMockRecorder) SignalError(channel, message interface{}, ctx ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{channel, message}, ctx...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignalError", reflect.TypeOf((*MockLogger)(nil).SignalError), varargs...)
}

// SignalFatal mocks base method.
func (m *MockLogger) SignalFatal(channel, message string, ctx ...flam.Bag) {
	m.ctrl.T.Helper()
	varargs := []interface{}{channel, message}
	for _, a := range ctx {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "SignalFatal", varargs...)
}

// SignalFatal indicates an expected call of SignalFatal.
func (mr *MockLoggerMockRecorder) SignalFatal(channel, message interface{}, ctx ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{channel, message}, ctx...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignalFatal", reflect.TypeOf((*MockLogger)(nil).SignalFatal), varargs...)
}

// SignalInfo mocks base method.
func (m *MockLogger) SignalInfo(channel, message string, ctx ...flam.Bag) {
	m.ctrl.T.Helper()
	varargs := []interface{}{channel, message}
	for _, a := range ctx {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "SignalInfo", varargs...)
}

// SignalInfo indicates an expected call of SignalInfo.
func (mr *MockLoggerMockRecorder) SignalInfo(channel, message interface{}, ctx ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{channel, message}, ctx...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignalInfo", reflect.TypeOf((*MockLogger)(nil).SignalInfo), varargs...)
}

// SignalNotice mocks base method.
func (m *MockLogger) SignalNotice(channel, message string, ctx ...flam.Bag) {
	m.ctrl.T.Helper()
	varargs := []interface{}{channel, message}
	for _, a := range ctx {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "SignalNotice", varargs...)
}

// SignalNotice indicates an expected call of SignalNotice.
func (mr *MockLoggerMockRecorder) SignalNotice(channel, message interface{}, ctx ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{channel, message}, ctx...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignalNotice", reflect.TypeOf((*MockLogger)(nil).SignalNotice), varargs...)
}

// SignalWarning mocks base method.
func (m *MockLogger) SignalWarning(channel, message string, ctx ...flam.Bag) {
	m.ctrl.T.Helper()
	varargs := []interface{}{channel, message}
	for _, a := range ctx {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "SignalWarning", varargs...)
}

// SignalWarning indicates an expected call of SignalWarning.
func (mr *MockLoggerMockRecorder) SignalWarning(channel, message interface{}, ctx ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{channel, message}, ctx...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignalWarning", reflect.TypeOf((*MockLogger)(nil).SignalWarning), varargs...)
}
