// Code generated by MockGen. DO NOT EDIT.
// Source: log_stream.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	flam "github.com/cjdias/flam-in-go"
	gomock "github.com/golang/mock/gomock"
)

// MockLogStream is a mock of LogStream interface.
type MockLogStream struct {
	ctrl     *gomock.Controller
	recorder *MockLogStreamMockRecorder
}

// MockLogStreamMockRecorder is the mock recorder for MockLogStream.
type MockLogStreamMockRecorder struct {
	mock *MockLogStream
}

// NewMockLogStream creates a new mock instance.
func NewMockLogStream(ctrl *gomock.Controller) *MockLogStream {
	mock := &MockLogStream{ctrl: ctrl}
	mock.recorder = &MockLogStreamMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogStream) EXPECT() *MockLogStreamMockRecorder {
	return m.recorder
}

// AddChannel mocks base method.
func (m *MockLogStream) AddChannel(channel string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddChannel", channel)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddChannel indicates an expected call of AddChannel.
func (mr *MockLogStreamMockRecorder) AddChannel(channel interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddChannel", reflect.TypeOf((*MockLogStream)(nil).AddChannel), channel)
}

// Broadcast mocks base method.
func (m *MockLogStream) Broadcast(timestamp time.Time, level flam.LogLevel, message string, ctx flam.Bag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Broadcast", timestamp, level, message, ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Broadcast indicates an expected call of Broadcast.
func (mr *MockLogStreamMockRecorder) Broadcast(timestamp, level, message, ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Broadcast", reflect.TypeOf((*MockLogStream)(nil).Broadcast), timestamp, level, message, ctx)
}

// Close mocks base method.
func (m *MockLogStream) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockLogStreamMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockLogStream)(nil).Close))
}

// GetLevel mocks base method.
func (m *MockLogStream) GetLevel() flam.LogLevel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLevel")
	ret0, _ := ret[0].(flam.LogLevel)
	return ret0
}

// GetLevel indicates an expected call of GetLevel.
func (mr *MockLogStreamMockRecorder) GetLevel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLevel", reflect.TypeOf((*MockLogStream)(nil).GetLevel))
}

// HasChannel mocks base method.
func (m *MockLogStream) HasChannel(channel string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasChannel", channel)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasChannel indicates an expected call of HasChannel.
func (mr *MockLogStreamMockRecorder) HasChannel(channel interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasChannel", reflect.TypeOf((*MockLogStream)(nil).HasChannel), channel)
}

// ListChannels mocks base method.
func (m *MockLogStream) ListChannels() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChannels")
	ret0, _ := ret[0].([]string)
	return ret0
}

// ListChannels indicates an expected call of ListChannels.
func (mr *MockLogStreamMockRecorder) ListChannels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChannels", reflect.TypeOf((*MockLogStream)(nil).ListChannels))
}

// RemoveAllChannels mocks base method.
func (m *MockLogStream) RemoveAllChannels() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAllChannels")
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAllChannels indicates an expected call of RemoveAllChannels.
func (mr *MockLogStreamMockRecorder) RemoveAllChannels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAllChannels", reflect.TypeOf((*MockLogStream)(nil).RemoveAllChannels))
}

// RemoveChannel mocks base method.
func (m *MockLogStream) RemoveChannel(channel string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveChannel", channel)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveChannel indicates an expected call of RemoveChannel.
func (mr *MockLogStreamMockRecorder) RemoveChannel(channel interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveChannel", reflect.TypeOf((*MockLogStream)(nil).RemoveChannel), channel)
}

// SetLevel mocks base method.
func (m *MockLogStream) SetLevel(level flam.LogLevel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLevel", level)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLevel indicates an expected call of SetLevel.
func (mr *MockLogStreamMockRecorder) SetLevel(level interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLevel", reflect.TypeOf((*MockLogStream)(nil).SetLevel), level)
}

// Signal mocks base method.
func (m *MockLogStream) Signal(timestamp time.Time, level flam.LogLevel, channel, message string, ctx flam.Bag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signal", timestamp, level, channel, message, ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Signal indicates an expected call of Signal.
func (mr *MockLogStreamMockRecorder) Signal(timestamp, level, channel, message, ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockLogStream)(nil).Signal), timestamp, level, channel, message, ctx)
}
