// Code generated by MockGen. DO NOT EDIT.
// Source: log_serializer.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	flam "github.com/cjdias/flam-in-go"
	gomock "github.com/golang/mock/gomock"
)

// MockLogSerializer is a mock of LogSerializer interface.
type MockLogSerializer struct {
	ctrl     *gomock.Controller
	recorder *MockLogSerializerMockRecorder
}

// MockLogSerializerMockRecorder is the mock recorder for MockLogSerializer.
type MockLogSerializerMockRecorder struct {
	mock *MockLogSerializer
}

// NewMockLogSerializer creates a new mock instance.
func NewMockLogSerializer(ctrl *gomock.Controller) *MockLogSerializer {
	mock := &MockLogSerializer{ctrl: ctrl}
	mock.recorder = &MockLogSerializerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogSerializer) EXPECT() *MockLogSerializerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockLogSerializer) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockLogSerializerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockLogSerializer)(nil).Close))
}

// Serialize mocks base method.
func (m *MockLogSerializer) Serialize(timestamp time.Time, level flam.LogLevel, message string, ctx flam.Bag) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Serialize", timestamp, level, message, ctx)
	ret0, _ := ret[0].(string)
	return ret0
}

// Serialize indicates an expected call of Serialize.
func (mr *MockLogSerializerMockRecorder) Serialize(timestamp, level, message, ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Serialize", reflect.TypeOf((*MockLogSerializer)(nil).Serialize), timestamp, level, message, ctx)
}
