// Code generated by MockGen. DO NOT EDIT.
// Source: migrator_logger.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	flam "github.com/cjdias/flam-in-go"
	gomock "github.com/golang/mock/gomock"
)

// MockMigratorLogger is a mock of MigratorLogger interface.
type MockMigratorLogger struct {
	ctrl     *gomock.Controller
	recorder *MockMigratorLoggerMockRecorder
}

// MockMigratorLoggerMockRecorder is the mock recorder for MockMigratorLogger.
type MockMigratorLoggerMockRecorder struct {
	mock *MockMigratorLogger
}

// NewMockMigratorLogger creates a new mock instance.
func NewMockMigratorLogger(ctrl *gomock.Controller) *MockMigratorLogger {
	mock := &MockMigratorLogger{ctrl: ctrl}
	mock.recorder = &MockMigratorLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMigratorLogger) EXPECT() *MockMigratorLoggerMockRecorder {
	return m.recorder
}

// LogDownDone mocks base method.
func (m *MockMigratorLogger) LogDownDone(info flam.MigrationInfo) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogDownDone", info)
}

// LogDownDone indicates an expected call of LogDownDone.
func (mr *MockMigratorLoggerMockRecorder) LogDownDone(info interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogDownDone", reflect.TypeOf((*MockMigratorLogger)(nil).LogDownDone), info)
}

// LogDownError mocks base method.
func (m *MockMigratorLogger) LogDownError(info flam.MigrationInfo, e error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogDownError", info, e)
}

// LogDownError indicates an expected call of LogDownError.
func (mr *MockMigratorLoggerMockRecorder) LogDownError(info, e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogDownError", reflect.TypeOf((*MockMigratorLogger)(nil).LogDownError), info, e)
}

// LogDownStart mocks base method.
func (m *MockMigratorLogger) LogDownStart(info flam.MigrationInfo) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogDownStart", info)
}

// LogDownStart indicates an expected call of LogDownStart.
func (mr *MockMigratorLoggerMockRecorder) LogDownStart(info interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogDownStart", reflect.TypeOf((*MockMigratorLogger)(nil).LogDownStart), info)
}

// LogUpDone mocks base method.
func (m *MockMigratorLogger) LogUpDone(info flam.MigrationInfo) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogUpDone", info)
}

// LogUpDone indicates an expected call of LogUpDone.
func (mr *MockMigratorLoggerMockRecorder) LogUpDone(info interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogUpDone", reflect.TypeOf((*MockMigratorLogger)(nil).LogUpDone), info)
}

// LogUpError mocks base method.
func (m *MockMigratorLogger) LogUpError(info flam.MigrationInfo, e error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogUpError", info, e)
}

// LogUpError indicates an expected call of LogUpError.
func (mr *MockMigratorLoggerMockRecorder) LogUpError(info, e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogUpError", reflect.TypeOf((*MockMigratorLogger)(nil).LogUpError), info, e)
}

// LogUpStart mocks base method.
func (m *MockMigratorLogger) LogUpStart(info flam.MigrationInfo) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogUpStart", info)
}

// LogUpStart indicates an expected call of LogUpStart.
func (mr *MockMigratorLoggerMockRecorder) LogUpStart(info interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogUpStart", reflect.TypeOf((*MockMigratorLogger)(nil).LogUpStart), info)
}
