// Code generated by MockGen. DO NOT EDIT.
// Source: migrator.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	flam "github.com/cjdias/flam-in-go"
	gomock "github.com/golang/mock/gomock"
)

// MockMigrator is a mock of Migrator interface.
type MockMigrator struct {
	ctrl     *gomock.Controller
	recorder *MockMigratorMockRecorder
}

// MockMigratorMockRecorder is the mock recorder for MockMigrator.
type MockMigratorMockRecorder struct {
	mock *MockMigrator
}

// NewMockMigrator creates a new mock instance.
func NewMockMigrator(ctrl *gomock.Controller) *MockMigrator {
	mock := &MockMigrator{ctrl: ctrl}
	mock.recorder = &MockMigratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMigrator) EXPECT() *MockMigratorMockRecorder {
	return m.recorder
}

// CanDown mocks base method.
func (m *MockMigrator) CanDown() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanDown")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanDown indicates an expected call of CanDown.
func (mr *MockMigratorMockRecorder) CanDown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanDown", reflect.TypeOf((*MockMigrator)(nil).CanDown))
}

// CanUp mocks base method.
func (m *MockMigrator) CanUp() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanUp")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanUp indicates an expected call of CanUp.
func (mr *MockMigratorMockRecorder) CanUp() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanUp", reflect.TypeOf((*MockMigrator)(nil).CanUp))
}

// Current mocks base method.
func (m *MockMigrator) Current() (*flam.MigrationInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Current")
	ret0, _ := ret[0].(*flam.MigrationInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Current indicates an expected call of Current.
func (mr *MockMigratorMockRecorder) Current() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Current", reflect.TypeOf((*MockMigrator)(nil).Current))
}

// Down mocks base method.
func (m *MockMigrator) Down() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Down")
	ret0, _ := ret[0].(error)
	return ret0
}

// Down indicates an expected call of Down.
func (mr *MockMigratorMockRecorder) Down() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Down", reflect.TypeOf((*MockMigrator)(nil).Down))
}

// DownAll mocks base method.
func (m *MockMigrator) DownAll() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownAll")
	ret0, _ := ret[0].(error)
	return ret0
}

// DownAll indicates an expected call of DownAll.
func (mr *MockMigratorMockRecorder) DownAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownAll", reflect.TypeOf((*MockMigrator)(nil).DownAll))
}

// List mocks base method.
func (m *MockMigrator) List() ([]flam.MigrationInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]flam.MigrationInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMigratorMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMigrator)(nil).List))
}

// Up mocks base method.
func (m *MockMigrator) Up() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Up")
	ret0, _ := ret[0].(error)
	return ret0
}

// Up indicates an expected call of Up.
func (mr *MockMigratorMockRecorder) Up() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Up", reflect.TypeOf((*MockMigrator)(nil).Up))
}

// UpAll mocks base method.
func (m *MockMigrator) UpAll() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpAll")
	ret0, _ := ret[0].(error)
	return ret0
}

// UpAll indicates an expected call of UpAll.
func (mr *MockMigratorMockRecorder) UpAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpAll", reflect.TypeOf((*MockMigrator)(nil).UpAll))
}
