// Code generated by MockGen. DO NOT EDIT.
// Source: provider.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	flam "github.com/cjdias/flam-in-go"
	gomock "github.com/golang/mock/gomock"
	dig "go.uber.org/dig"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// Id mocks base method.
func (m *MockProvider) Id() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Id")
	ret0, _ := ret[0].(string)
	return ret0
}

// Id indicates an expected call of Id.
func (mr *MockProviderMockRecorder) Id() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Id", reflect.TypeOf((*MockProvider)(nil).Id))
}

// Register mocks base method.
func (m *MockProvider) Register(container *dig.Container) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", container)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockProviderMockRecorder) Register(container interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockProvider)(nil).Register), container)
}

// MockConfigurableProvider is a mock of ConfigurableProvider interface.
type MockConfigurableProvider struct {
	ctrl     *gomock.Controller
	recorder *MockConfigurableProviderMockRecorder
}

// MockConfigurableProviderMockRecorder is the mock recorder for MockConfigurableProvider.
type MockConfigurableProviderMockRecorder struct {
	mock *MockConfigurableProvider
}

// NewMockConfigurableProvider creates a new mock instance.
func NewMockConfigurableProvider(ctrl *gomock.Controller) *MockConfigurableProvider {
	mock := &MockConfigurableProvider{ctrl: ctrl}
	mock.recorder = &MockConfigurableProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigurableProvider) EXPECT() *MockConfigurableProviderMockRecorder {
	return m.recorder
}

// Config mocks base method.
func (m *MockConfigurableProvider) Config(config *flam.Bag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config", config)
	ret0, _ := ret[0].(error)
	return ret0
}

// Config indicates an expected call of Config.
func (mr *MockConfigurableProviderMockRecorder) Config(config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockConfigurableProvider)(nil).Config), config)
}

// Id mocks base method.
func (m *MockConfigurableProvider) Id() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Id")
	ret0, _ := ret[0].(string)
	return ret0
}

// Id indicates an expected call of Id.
func (mr *MockConfigurableProviderMockRecorder) Id() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Id", reflect.TypeOf((*MockConfigurableProvider)(nil).Id))
}

// Register mocks base method.
func (m *MockConfigurableProvider) Register(container *dig.Container) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", container)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockConfigurableProviderMockRecorder) Register(container interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockConfigurableProvider)(nil).Register), container)
}

// MockBootableProvider is a mock of BootableProvider interface.
type MockBootableProvider struct {
	ctrl     *gomock.Controller
	recorder *MockBootableProviderMockRecorder
}

// MockBootableProviderMockRecorder is the mock recorder for MockBootableProvider.
type MockBootableProviderMockRecorder struct {
	mock *MockBootableProvider
}

// NewMockBootableProvider creates a new mock instance.
func NewMockBootableProvider(ctrl *gomock.Controller) *MockBootableProvider {
	mock := &MockBootableProvider{ctrl: ctrl}
	mock.recorder = &MockBootableProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBootableProvider) EXPECT() *MockBootableProviderMockRecorder {
	return m.recorder
}

// Boot mocks base method.
func (m *MockBootableProvider) Boot(container *dig.Container) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Boot", container)
	ret0, _ := ret[0].(error)
	return ret0
}

// Boot indicates an expected call of Boot.
func (mr *MockBootableProviderMockRecorder) Boot(container interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Boot", reflect.TypeOf((*MockBootableProvider)(nil).Boot), container)
}

// Id mocks base method.
func (m *MockBootableProvider) Id() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Id")
	ret0, _ := ret[0].(string)
	return ret0
}

// Id indicates an expected call of Id.
func (mr *MockBootableProviderMockRecorder) Id() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Id", reflect.TypeOf((*MockBootableProvider)(nil).Id))
}

// Register mocks base method.
func (m *MockBootableProvider) Register(container *dig.Container) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", container)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockBootableProviderMockRecorder) Register(container interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockBootableProvider)(nil).Register), container)
}

// MockRunnableProvider is a mock of RunnableProvider interface.
type MockRunnableProvider struct {
	ctrl     *gomock.Controller
	recorder *MockRunnableProviderMockRecorder
}

// MockRunnableProviderMockRecorder is the mock recorder for MockRunnableProvider.
type MockRunnableProviderMockRecorder struct {
	mock *MockRunnableProvider
}

// NewMockRunnableProvider creates a new mock instance.
func NewMockRunnableProvider(ctrl *gomock.Controller) *MockRunnableProvider {
	mock := &MockRunnableProvider{ctrl: ctrl}
	mock.recorder = &MockRunnableProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRunnableProvider) EXPECT() *MockRunnableProviderMockRecorder {
	return m.recorder
}

// Id mocks base method.
func (m *MockRunnableProvider) Id() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Id")
	ret0, _ := ret[0].(string)
	return ret0
}

// Id indicates an expected call of Id.
func (mr *MockRunnableProviderMockRecorder) Id() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Id", reflect.TypeOf((*MockRunnableProvider)(nil).Id))
}

// Register mocks base method.
func (m *MockRunnableProvider) Register(container *dig.Container) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", container)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockRunnableProviderMockRecorder) Register(container interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockRunnableProvider)(nil).Register), container)
}

// Run mocks base method.
func (m *MockRunnableProvider) Run(container *dig.Container) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", container)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockRunnableProviderMockRecorder) Run(container interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockRunnableProvider)(nil).Run), container)
}

// MockClosableProvider is a mock of ClosableProvider interface.
type MockClosableProvider struct {
	ctrl     *gomock.Controller
	recorder *MockClosableProviderMockRecorder
}

// MockClosableProviderMockRecorder is the mock recorder for MockClosableProvider.
type MockClosableProviderMockRecorder struct {
	mock *MockClosableProvider
}

// NewMockClosableProvider creates a new mock instance.
func NewMockClosableProvider(ctrl *gomock.Controller) *MockClosableProvider {
	mock := &MockClosableProvider{ctrl: ctrl}
	mock.recorder = &MockClosableProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClosableProvider) EXPECT() *MockClosableProviderMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockClosableProvider) Close(container *dig.Container) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", container)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockClosableProviderMockRecorder) Close(container interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClosableProvider)(nil).Close), container)
}

// Id mocks base method.
func (m *MockClosableProvider) Id() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Id")
	ret0, _ := ret[0].(string)
	return ret0
}

// Id indicates an expected call of Id.
func (mr *MockClosableProviderMockRecorder) Id() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Id", reflect.TypeOf((*MockClosableProvider)(nil).Id))
}

// Register mocks base method.
func (m *MockClosableProvider) Register(container *dig.Container) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", container)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockClosableProviderMockRecorder) Register(container interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockClosableProvider)(nil).Register), container)
}
