// Code generated by MockGen. DO NOT EDIT.
// Source: timer.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockTimer is a mock of Timer interface.
type MockTimer struct {
	ctrl     *gomock.Controller
	recorder *MockTimerMockRecorder
}

// MockTimerMockRecorder is the mock recorder for MockTimer.
type MockTimerMockRecorder struct {
	mock *MockTimer
}

// NewMockTimer creates a new mock instance.
func NewMockTimer(ctrl *gomock.Controller) *MockTimer {
	mock := &MockTimer{ctrl: ctrl}
	mock.recorder = &MockTimerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimer) EXPECT() *MockTimerMockRecorder {
	return m.recorder
}

// Date mocks base method.
func (m *MockTimer) Date(year int, month time.Month, day, hour, min, sec, nsec int, loc *time.Location) time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Date", year, month, day, hour, min, sec, nsec, loc)
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Date indicates an expected call of Date.
func (mr *MockTimerMockRecorder) Date(year, month, day, hour, min, sec, nsec, loc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Date", reflect.TypeOf((*MockTimer)(nil).Date), year, month, day, hour, min, sec, nsec, loc)
}

// FixedZone mocks base method.
func (m *MockTimer) FixedZone(name string, offset int) *time.Location {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FixedZone", name, offset)
	ret0, _ := ret[0].(*time.Location)
	return ret0
}

// FixedZone indicates an expected call of FixedZone.
func (mr *MockTimerMockRecorder) FixedZone(name, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FixedZone", reflect.TypeOf((*MockTimer)(nil).FixedZone), name, offset)
}

// LoadLocation mocks base method.
func (m *MockTimer) LoadLocation(name string) (*time.Location, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadLocation", name)
	ret0, _ := ret[0].(*time.Location)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadLocation indicates an expected call of LoadLocation.
func (mr *MockTimerMockRecorder) LoadLocation(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadLocation", reflect.TypeOf((*MockTimer)(nil).LoadLocation), name)
}

// Now mocks base method.
func (m *MockTimer) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockTimerMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockTimer)(nil).Now))
}

// Parse mocks base method.
func (m *MockTimer) Parse(layout, value string) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", layout, value)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockTimerMockRecorder) Parse(layout, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockTimer)(nil).Parse), layout, value)
}

// ParseDuration mocks base method.
func (m *MockTimer) ParseDuration(s string) (time.Duration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseDuration", s)
	ret0, _ := ret[0].(time.Duration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseDuration indicates an expected call of ParseDuration.
func (mr *MockTimerMockRecorder) ParseDuration(s interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseDuration", reflect.TypeOf((*MockTimer)(nil).ParseDuration), s)
}

// ParseInLocation mocks base method.
func (m *MockTimer) ParseInLocation(layout, value string, loc *time.Location) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseInLocation", layout, value, loc)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseInLocation indicates an expected call of ParseInLocation.
func (mr *MockTimerMockRecorder) ParseInLocation(layout, value, loc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseInLocation", reflect.TypeOf((*MockTimer)(nil).ParseInLocation), layout, value, loc)
}

// Since mocks base method.
func (m *MockTimer) Since(t time.Time) time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Since", t)
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// Since indicates an expected call of Since.
func (mr *MockTimerMockRecorder) Since(t interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Since", reflect.TypeOf((*MockTimer)(nil).Since), t)
}

// Unix mocks base method.
func (m *MockTimer) Unix(sec, nsec int64) time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unix", sec, nsec)
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Unix indicates an expected call of Unix.
func (mr *MockTimerMockRecorder) Unix(sec, nsec interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unix", reflect.TypeOf((*MockTimer)(nil).Unix), sec, nsec)
}

// UnixMicro mocks base method.
func (m *MockTimer) UnixMicro(usec int64) time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnixMicro", usec)
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// UnixMicro indicates an expected call of UnixMicro.
func (mr *MockTimerMockRecorder) UnixMicro(usec interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnixMicro", reflect.TypeOf((*MockTimer)(nil).UnixMicro), usec)
}

// UnixMilli mocks base method.
func (m *MockTimer) UnixMilli(msec int64) time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnixMilli", msec)
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// UnixMilli indicates an expected call of UnixMilli.
func (mr *MockTimerMockRecorder) UnixMilli(msec interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnixMilli", reflect.TypeOf((*MockTimer)(nil).UnixMilli), msec)
}

// Until mocks base method.
func (m *MockTimer) Until(t time.Time) time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Until", t)
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// Until indicates an expected call of Until.
func (mr *MockTimerMockRecorder) Until(t interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Until", reflect.TypeOf((*MockTimer)(nil).Until), t)
}
