// Code generated by MockGen. DO NOT EDIT.
// Source: trigger_factory.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	flam "github.com/cjdias/flam-in-go"
	gomock "github.com/golang/mock/gomock"
)

// MockTriggerFactory is a mock of TriggerFactory interface.
type MockTriggerFactory struct {
	ctrl     *gomock.Controller
	recorder *MockTriggerFactoryMockRecorder
}

// MockTriggerFactoryMockRecorder is the mock recorder for MockTriggerFactory.
type MockTriggerFactoryMockRecorder struct {
	mock *MockTriggerFactory
}

// NewMockTriggerFactory creates a new mock instance.
func NewMockTriggerFactory(ctrl *gomock.Controller) *MockTriggerFactory {
	mock := &MockTriggerFactory{ctrl: ctrl}
	mock.recorder = &MockTriggerFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTriggerFactory) EXPECT() *MockTriggerFactoryMockRecorder {
	return m.recorder
}

// NewPulse mocks base method.
func (m *MockTriggerFactory) NewPulse(delay time.Duration, callback flam.TriggerCallback) (flam.Trigger, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewPulse", delay, callback)
	ret0, _ := ret[0].(flam.Trigger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewPulse indicates an expected call of NewPulse.
func (mr *MockTriggerFactoryMockRecorder) NewPulse(delay, callback interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewPulse", reflect.TypeOf((*MockTriggerFactory)(nil).NewPulse), delay, callback)
}

// NewRecurring mocks base method.
func (m *MockTriggerFactory) NewRecurring(delay time.Duration, callback flam.TriggerCallback) (flam.Trigger, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewRecurring", delay, callback)
	ret0, _ := ret[0].(flam.Trigger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewRecurring indicates an expected call of NewRecurring.
func (mr *MockTriggerFactoryMockRecorder) NewRecurring(delay, callback interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewRecurring", reflect.TypeOf((*MockTriggerFactory)(nil).NewRecurring), delay, callback)
}
