// Code generated by MockGen. DO NOT EDIT.
// Source: validator_error_converter_creator.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	flam "github.com/cjdias/flam-in-go"
	gomock "github.com/golang/mock/gomock"
)

// MockValidatorErrorConverterCreator is a mock of ValidatorErrorConverterCreator interface.
type MockValidatorErrorConverterCreator struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorErrorConverterCreatorMockRecorder
}

// MockValidatorErrorConverterCreatorMockRecorder is the mock recorder for MockValidatorErrorConverterCreator.
type MockValidatorErrorConverterCreatorMockRecorder struct {
	mock *MockValidatorErrorConverterCreator
}

// NewMockValidatorErrorConverterCreator creates a new mock instance.
func NewMockValidatorErrorConverterCreator(ctrl *gomock.Controller) *MockValidatorErrorConverterCreator {
	mock := &MockValidatorErrorConverterCreator{ctrl: ctrl}
	mock.recorder = &MockValidatorErrorConverterCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidatorErrorConverterCreator) EXPECT() *MockValidatorErrorConverterCreatorMockRecorder {
	return m.recorder
}

// Accept mocks base method.
func (m *MockValidatorErrorConverterCreator) Accept(config flam.Bag) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Accept", config)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Accept indicates an expected call of Accept.
func (mr *MockValidatorErrorConverterCreatorMockRecorder) Accept(config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Accept", reflect.TypeOf((*MockValidatorErrorConverterCreator)(nil).Accept), config)
}

// Create mocks base method.
func (m *MockValidatorErrorConverterCreator) Create(config flam.Bag) (flam.ValidatorErrorConverter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", config)
	ret0, _ := ret[0].(flam.ValidatorErrorConverter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockValidatorErrorConverterCreatorMockRecorder) Create(config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockValidatorErrorConverterCreator)(nil).Create), config)
}
