// Code generated by MockGen. DO NOT EDIT.
// Source: validator_error_converter.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	flam "github.com/cjdias/flam-in-go"
	gomock "github.com/golang/mock/gomock"
)

// MockValidatorErrorConverter is a mock of ValidatorErrorConverter interface.
type MockValidatorErrorConverter struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorErrorConverterMockRecorder
}

// MockValidatorErrorConverterMockRecorder is the mock recorder for MockValidatorErrorConverter.
type MockValidatorErrorConverterMockRecorder struct {
	mock *MockValidatorErrorConverter
}

// NewMockValidatorErrorConverter creates a new mock instance.
func NewMockValidatorErrorConverter(ctrl *gomock.Controller) *MockValidatorErrorConverter {
	mock := &MockValidatorErrorConverter{ctrl: ctrl}
	mock.recorder = &MockValidatorErrorConverterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidatorErrorConverter) EXPECT() *MockValidatorErrorConverterMockRecorder {
	return m.recorder
}

// Convert mocks base method.
func (m *MockValidatorErrorConverter) Convert(errors []flam.ValidationError) any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Convert", errors)
	ret0, _ := ret[0].(any)
	return ret0
}

// Convert indicates an expected call of Convert.
func (mr *MockValidatorErrorConverterMockRecorder) Convert(errors interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Convert", reflect.TypeOf((*MockValidatorErrorConverter)(nil).Convert), errors)
}
