// Code generated by MockGen. DO NOT EDIT.
// Source: validator_parser.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	flam "github.com/cjdias/flam-in-go"
	validator "github.com/go-playground/validator/v10"
	gomock "github.com/golang/mock/gomock"
)

// MockValidatorParser is a mock of ValidatorParser interface.
type MockValidatorParser struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorParserMockRecorder
}

// MockValidatorParserMockRecorder is the mock recorder for MockValidatorParser.
type MockValidatorParserMockRecorder struct {
	mock *MockValidatorParser
}

// NewMockValidatorParser creates a new mock instance.
func NewMockValidatorParser(ctrl *gomock.Controller) *MockValidatorParser {
	mock := &MockValidatorParser{ctrl: ctrl}
	mock.recorder = &MockValidatorParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidatorParser) EXPECT() *MockValidatorParserMockRecorder {
	return m.recorder
}

// AddTagCode mocks base method.
func (m *MockValidatorParser) AddTagCode(tag string, code int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddTagCode", tag, code)
}

// AddTagCode indicates an expected call of AddTagCode.
func (mr *MockValidatorParserMockRecorder) AddTagCode(tag, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTagCode", reflect.TypeOf((*MockValidatorParser)(nil).AddTagCode), tag, code)
}

// Parse mocks base method.
func (m *MockValidatorParser) Parse(value any, errs validator.ValidationErrors) []flam.ValidationError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", value, errs)
	ret0, _ := ret[0].([]flam.ValidationError)
	return ret0
}

// Parse indicates an expected call of Parse.
func (mr *MockValidatorParserMockRecorder) Parse(value, errs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockValidatorParser)(nil).Parse), value, errs)
}
