// Code generated by MockGen. DO NOT EDIT.
// Source: watchdog_logger.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockWatchdogLogger is a mock of WatchdogLogger interface.
type MockWatchdogLogger struct {
	ctrl     *gomock.Controller
	recorder *MockWatchdogLoggerMockRecorder
}

// MockWatchdogLoggerMockRecorder is the mock recorder for MockWatchdogLogger.
type MockWatchdogLoggerMockRecorder struct {
	mock *MockWatchdogLogger
}

// NewMockWatchdogLogger creates a new mock instance.
func NewMockWatchdogLogger(ctrl *gomock.Controller) *MockWatchdogLogger {
	mock := &MockWatchdogLogger{ctrl: ctrl}
	mock.recorder = &MockWatchdogLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWatchdogLogger) EXPECT() *MockWatchdogLoggerMockRecorder {
	return m.recorder
}

// LogDone mocks base method.
func (m *MockWatchdogLogger) LogDone(id string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogDone", id)
}

// LogDone indicates an expected call of LogDone.
func (mr *MockWatchdogLoggerMockRecorder) LogDone(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogDone", reflect.TypeOf((*MockWatchdogLogger)(nil).LogDone), id)
}

// LogError mocks base method.
func (m *MockWatchdogLogger) LogError(id string, e error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogError", id, e)
}

// LogError indicates an expected call of LogError.
func (mr *MockWatchdogLoggerMockRecorder) LogError(id, e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogError", reflect.TypeOf((*MockWatchdogLogger)(nil).LogError), id, e)
}

// LogStart mocks base method.
func (m *MockWatchdogLogger) LogStart(id string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogStart", id)
}

// LogStart indicates an expected call of LogStart.
func (mr *MockWatchdogLoggerMockRecorder) LogStart(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogStart", reflect.TypeOf((*MockWatchdogLogger)(nil).LogStart), id)
}
