version: '3'

includes:
  git:
    taskfile: ./tools/taskfiles/git.yml

  go:
    taskfile: ./tools/taskfiles/go.yml

  quality:
    taskfile: ./tools/taskfiles/quality.yml

tasks:
  default:
    cmds:
      - task --list-all
